tasks/urls.py
from django.urls import path

from tasks.views import (
    TaskListView,
    TaskCreateView,
    TagListView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView,
    TaskUpdateStatusView,
)

app_name = "tasks"

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path(
        "tasks/<int:pk>/update_status/",
        TaskUpdateStatusView.as_view(),
        name="task-update-status",
    ),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
]

tasks/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ("is_done", "-created_at")

    def __str__(self) -> str:
        return self.title

tasks/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from tasks.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    template_name = "tasks/task_list.html"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TaskUpdateStatusView(generic.UpdateView):
    model = Task
    fields = ("is_done",)

    def post(self, request, *args, **kwargs) -> HttpResponseRedirect:
        task = self.get_object()
        if task.is_done:
            task.is_done = False
        else:
            task.is_done = True
        task.save()
        return HttpResponseRedirect(reverse("tasks:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}<title>To-Do List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid mt-2">
      <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
      </div>
    </div>
  </body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'tasks:task-list' %}" class="text-decoration-none">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}" class="text-decoration-none">Tags</a></li>
</ul>

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1 class="mb-3">Delete this tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <button onclick="javascript:history.back()" class="btn btn-secondary">Cancel</button>
  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post">
    {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">{{ object|yesno:"Update,Create" }}</button>
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}
{% block content %}
  <h1 class="mb-3">
    Tags
    <a href="{% url 'tasks:tag-create' %}">
      <button class="btn btn-primary float-end m-2">Add</button>
    </a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'tasks:tag-update' pk=tag.id %}" class="btn btn-secondary">Update</a>
          </td>
          <td>
            <a href="{% url 'tasks:tag-delete' pk=tag.id %}" class="btn btn-danger">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}
{% endblock %}

templates/tasks/task_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>Create task</h1>
  <form action="" method="post">
    {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">Create</button>
  </form>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}
{% block content %}
  <h1 class="mb-2">
    TODO List
    <a href="{% url 'tasks:task-create' %}">
      <button class="btn btn-primary float-end m-2">Add task</button>
    </a>
  </h1>
  {% for task in task_list %}
    <h4>
      {{ task.title }}
     {% if task.is_done %}
       <span class="text-success">Done</span>
       <form action="{% url 'tasks:task-update-status' pk=task.id %}" method="post">
        {% csrf_token %}
          <button class="btn btn-secondary float-end m-2">Undo</button>
       </form>
     {% else %}
       <span class="text-danger">Not done</span>
       <form action="{% url 'tasks:task-update-status' pk=task.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success float-end m-2">Complete</button>
       </form>
     {% endif %}
    </h4>
    <p>{{ task.description }}</p>
    <p>
      Created: {{ task.created_at }}
    {% if task.deadline %}
      <span class="text-danger">Deadline: {{ task.deadline }}</span>
    {% endif %}
    </p>
    <p>
      Tags:
    {% for tag in task.tags.all %}
      {{ tag }} <a href="{% url 'tasks:tag-update' pk=tag.id %}" class="text-decoration-none">Update</a>
      <a href="{% url 'tasks:tag-delete' pk=tag.id %}" class="text-decoration-none">Delete</a>
    {% endfor %}
    </p>
    <hr>
  {% endfor %}
{% endblock %}